### ISSUE TITLE
Support riscv

### ISSUE THREAD

**Issue by yudjjdzl** [petrpavlu/valgrind-riscv64#1]
in order to support riscv,Made what changes?

**Comment by petrpavlu** [comment]
All current changes made to support RISC-V can be viewed by running `git diff remotes/origin/master..riscv64-linux` in the cloned repository. Most work is in the VEX library which needs to be able to decode RISC-V instructions into Valgrind's IR and vice versa provide a codegen of the IR to the RISC-V machine code.
