### ISSUE TITLE
Regtest fails on FreeBSD amd64

### ISSUE THREAD

**Issue by paulfloyd** [petrpavlu/valgrind-riscv64#11]
First, I get these

```
memcheck/tests/riscv64-linux/context_float (stdout)
memcheck/tests/riscv64-linux/context_float (stderr)
memcheck/tests/riscv64-linux/context_integer (stdout)
memcheck/tests/riscv64-linux/context_integer (stderr)
memcheck/tests/riscv64-linux/scalar      (stderr)
...
Unknown directory 'riscv64'. Please update check_headers_and_includes
```

I also get 2 new failures

memcheck/tests/leak-segv-jmp             (stderr)

That looks like a line number change due to added RISCV64 code in the .c file and the expected needs updating.

none/tests/libvexmultiarch_test          (stderr)

```
paulf> cat none/tests/libvexmultiarch_test*diff
--- libvexmultiarch_test.stderr.exp     2023-01-29 09:36:06.883182000 +0100
+++ libvexmultiarch_test.stderr.out     2023-01-29 10:16:07.617645000 +0100
@@ -0,0 +1 @@
+valgrind: ./libvexmultiarch_test: No such file or directory
```

I see that this is marked as 'disable for now'. As a quick fix you could put in the .vgtest

prereq: ! ../../test/arch_test riscv64

**Comment by petrpavlu** [comment]
Thanks for testing the port and your report.

> First, I get these
> 
> ```
> memcheck/tests/riscv64-linux/context_float (stdout)
> memcheck/tests/riscv64-linux/context_float (stderr)
> memcheck/tests/riscv64-linux/context_integer (stdout)
> memcheck/tests/riscv64-linux/context_integer (stderr)
> memcheck/tests/riscv64-linux/scalar      (stderr)

Fixed in 5d18e7d77c2cecede6af00b6add6bc140f1e4f1d.

> ...
> Unknown directory 'riscv64'. Please update check_headers_and_includes

The riscv64 directory holds only one downstream script and should be ignored, marked as such in b5b139c8d4066055f0a4c1a61f3f38f595f8294f.

> ```
> 
> I also get 2 new failures
> 
> memcheck/tests/leak-segv-jmp (stderr)
> 
> That looks like a line number change due to added RISCV64 code in the .c file and the expected needs updating.

Fixed in ad503ee37ae164aac0b07b2aefee6d6aa4c5a4be.

> none/tests/libvexmultiarch_test (stderr)
> 
> ```
> paulf> cat none/tests/libvexmultiarch_test*diff
> --- libvexmultiarch_test.stderr.exp     2023-01-29 09:36:06.883182000 +0100
> +++ libvexmultiarch_test.stderr.out     2023-01-29 10:16:07.617645000 +0100
> @@ -0,0 +1 @@
> +valgrind: ./libvexmultiarch_test: No such file or directory
> ```
> 
> I see that this is marked as 'disable for now'. As a quick fix you could put in the .vgtest
> 
> prereq: ! ../../test/arch_test riscv64

Oops, I didn't add a TODO note when disabling this test so completely forgot about it. Re-enabled the test in b383c1aa970a2a7e539ee603c8ff6c5cc59404c0 with a workaround on RISC-V.

Closing the bug as all mentioned problems should be addressed now.
