### ISSUE TITLE
Assignment in if statement

### ISSUE THREAD

**Issue by paulfloyd** [petrpavlu/valgrind-riscv64#18]
https://github.com/petrpavlu/valgrind-riscv64/blob/0a389c93602c9847eed7fd28fd2934c9e5721387/VEX/priv/guest_riscv64_toIR.c#L1621

```
priv/guest_riscv64_toIR.c:1621:14: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
 1621 |          if (fm = 0b1000)
      |              ^~
```

Should probably be "=="

**Comment by petrpavlu** [comment]
Thanks, fixed in 8107c9e58299e826eaa933abf83860bd4ee3cf50.
